version: '3.8'
services:
  api_weather:
    build: .
    restart: always
    ports:
      - "8000:8000"
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html
    depends_on:
      - api_weather