version: '3.8'

services:
  api_weather:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile-backend
    restart: always
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ../
      dockerfile: ./infra/Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - api_weather
